# Generated by Django 4.0.2 on 2022-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids_food_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kid',
            name='name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='kid',
            name='parents_email',
            field=models.EmailField(max_length=254),
        ),
    ]
